dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

language: rust

# before_install:
#   - \[ "${TARGET}" = "asmjs-unknown-emscripten" ]
#     && wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
#     && tar -xzvf emsdk-portable.tar.gz
#     && ./emsdk-portable/emsdk update
#     && ./emsdk-portable/emsdk list --old
#     && ./emsdk-portable/emsdk install clang-e1.35.0-64bit
#     && ./emsdk-portable/emsdk activate clang-e1.35.0-64bit
#     && ./emsdk-portable/emsdk install emscripten-1.37.16
#     && ./emsdk-portable/emsdk activate emscripten-1.37.16
#     && source ./emsdk-portable/emsdk_env.sh
#     && emcc -v

before_install:
  - \[ "${TARGET}" = "asmjs-unknown-emscripten" ]
    && git clone --depth 1 https://github.com/ni-kismet/emscripten-sdk.git || (cd emscripten-sdk && git remote update -p && git merge --ff-only origin/master && cd ..)
    && emscripten-sdk/emsdk activate --build=Release sdk-master-64bit
    && source emscripten-sdk/emsdk_env.sh
    && emcc -v

script:
  - cargo build --target $TARGET

env:
  - TARGET=asmjs-unknown-emscripten
