dist: trusty
sudo: false

language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "${TARGET}" = "asmjs-unknown-emscripten" ]; then
      (git clone --depth 1 https://github.com/ni-kismet/emscripten-sdk.git || (cd emscripten-sdk && git remote update -p && git merge --ff-only origin/master && cd ..))
      && emscripten-sdk/emsdk activate --build=Release sdk-master-64bit
      && source emscripten-sdk/emsdk_env.sh
      && emcc -v;
    fi
  - (rustup toolchain list | grep $TARGET) || rustup target install $TARGET

script:
  - cargo build --target $TARGET
  - cd demo && cargo build --target $TARGET

matrix:
  include:
    - os: linux
      env: TARGET=asmjs-unknown-emscripten
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: osx
      env: TARGET=i686-apple-darwin
