dist: trusty
sudo: required

language: rust

before_install:
  - \[ "${TARGET}" = "asmjs-unknown-emscripten" ]
    && wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
    && tar -xzvf emsdk-portable.tar.gz
    && ./emsdk-portable/emsdk update
    && ./emsdk-portable/emsdk list
    && ./emsdk-portable/emsdk install clang-e1.36.14-64bit
    && ./emsdk-portable/emsdk activate clang-e1.36.14-64bit
    && ./emsdk-portable/emsdk install emscripten-1.37.16
    && ./emsdk-portable/emsdk activate emscripten-1.37.16
    && source ./emsdk-portable/emsdk_env.sh
    && emcc -v

script:
  - cargo build --target $TARGET

env:
  - TARGET=asmjs-unknown-emscripten
