dist: trusty
sudo: false

language: rust


before_install:
  - if [ "${TARGET}" = "asmjs-unknown-emscripten" ] && [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "${TARGET}" = "asmjs-unknown-emscripten" ]; then
      (git clone --depth 1 https://github.com/ni-kismet/emscripten-sdk.git || (cd emscripten-sdk && git remote update -p && git merge --ff-only origin/master && cd ..))
      && ./emscripten-sdk/emsdk list
      && ./emscripten-sdk/emsdk activate --build=Release sdk-master-64bit
      && ./emscripten-sdk/emsdk list
      && source emscripten-sdk/emsdk_env.sh
      && emcc -v;
    fi
  - (rustup toolchain list | grep $TARGET) || rustup target install $TARGET

script:
  - cargo build --target $TARGET
  - cd demo && cargo build --target $TARGET

matrix:
  include:
    - os: linux
      env: TARGET=asmjs-unknown-emscripten
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      cache:
        directories:
        - emscripten-sdk
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: osx
      env: TARGET=i686-apple-darwin
    - os: osx
      env: TARGET=i386-apple-ios
    - os: osx
      env: TARGET=x86_64-apple-ios
    - os: osx
      env: TARGET=aarch64-apple-ios
    - os: osx
      env: TARGET=armv7-apple-ios
    - os: osx
      env: TARGET=armv7s-apple-ios
