dist: trusty
sudo: false

language: rust

before_install:
  - \[ "${TARGET}" = "asmjs-unknown-emscripten" ]
    && git clone --depth 1 https://github.com/ni-kismet/emscripten-sdk.git
    && (cd emscripten-sdk && git remote update -p && git merge --ff-only origin/master)
    && emscripten-sdk/emsdk activate --build=Release sdk-master-64bit
    && source emscripten-sdk/emsdk_env.sh
    && emcc -v

script:
  - cargo build --target $TARGET

env:
  - TARGET=asmjs-unknown-emscripten
