dist: trusty
sudo: required

language: rust

before_install:
  - \[ "${TARGET}" = "asmjs-unknown-emscripten" ]
    && sudo apt-get install libstdc++6
    && sudo apt-get update -q
    && sudo apt-get upgrade
    && sudo apt-get dist-upgrade
    && wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
    && tar -xzvf emsdk-portable.tar.gz
    && ./emsdk-portable/emsdk update
    && ./emsdk-portable/emsdk install latest 2> /dev/null > /dev/null
    && ./emsdk-portable/emsdk activate latest
    && source ./emsdk-portable/emsdk_env.sh
    && emcc -v

script:
  - cargo build --target $TARGET

env:
  - TARGET=asmjs-unknown-emscripten
